### PR TITLE
Add landing page for college essay contest

### PR DESCRIPTION
**Pull request by slightlyoffbeat**

### CODE REVIEW

**Comment by pmac** [comment]
I think we're trying to keep the static assets in the `content/marketing-assets/`

**Comment by craigcook** [comment]
LGTM. re: images, it looks like there are already store badges in /marketing-assets/web-ui/assets/ you can use instead of adding new ones

**Comment by slightlyoffbeat** [comment]
@craigcook I originally set out to use the existing assets, but they are all different sizes and some include negative space while others don't (currently the site uses a lot of negative margins, etc). Chose to use new ones instead.

**Review by craigcook — APPROVED** [review]
🎓

**Comment by slightlyoffbeat** [comment]
@pmac Thanks. Assets moved to /marketing-assets

**Pull request merged**
